$schema: "https://json.schemastore.org/prettierrc"
tabWidth: 4
semi: true
singleQuote: false
trailingComma: none
printWidth: 100
endOfLine: lf
plugins: [prettier-plugin-astro, prettier-plugin-tailwindcss]
